const arrayCoinsCountry = [
  "Australian Dollar",
  "Bulgarian Lev",
  "Brazilian Real",
  "Canadian Dollar",
  "Swiss Franc",
  "Chinese Renminbi Yuan",
  "Czech Koruna",
  "Danish Krone",
  "Euro",
  "British Pound",
  "Hong Kong Dollar",
  "Croatian Kuna",
  "Hungarian Forint",
  "Indonesian Rupiah",
  "Israeli New Sheqel",
  "Indian Rupee",
  "Icelandic Króna",
  "Japanese Yen",
  "South Korean Won",
  "Mexican Peso",
  "Malaysian Ringgit",
  "Norwegian Krone",
  "New Zealand Dollar",
  "Philippine Peso",
  "Polish Złoty",
  "Romanian Leu",
  "Swedish Krona",
  "Singapore Dollar",
  "Thai Baht",
  "Turkish Lira",
  "United States Dollar",
  "South African Rand",
];

const coinsCountry = {
  "Australian Dollar": "AUD",
  "Bulgarian Lev": "BGN",
  "Brazilian Real": "BRL",
  "Canadian Dollar": "CAD",
  "Swiss Franc": "CHF",
  "Chinese Renminbi Yuan": "CNY",
  "Czech Koruna": "CZK",
  "Danish Krone": "DKK",
  Euro: "EUR",
  "British Pound": "GBP",
  "Hong Kong Dollar": "HKD",
  "Croatian Kuna": "HRK",
  "Hungarian Forint": "HUF",
  "Indonesian Rupiah": "IDR",
  "Israeli New Sheqel": "ILS",
  "Indian Rupee": "INR",
  "Icelandic Króna": "ISK",
  "Japanese Yen": "JPY",
  "South Korean Won": "KRW",
  "Mexican Peso": "MXN",
  "Malaysian Ringgit": "MYR",
  "Norwegian Krone": "NOK",
  "New Zealand Dollar": "NZD",
  "Philippine Peso": "PHP",
  "Polish Złoty": "PLN",
  "Romanian Leu": "RON",
  "Swedish Krona": "SEK",
  "Singapore Dollar": "SGD",
  "Thai Baht": "THB",
  "Turkish Lira": "TRY",
  "United States Dollar": "USD",
  "South African Rand": "ZAR",
};

export { arrayCoinsCountry, coinsCountry };
