//Head
import Head from "next/head";
//Hooks
import { useEffect } from "react";
import { useRouter } from "next/router";
//Componentes
import Splash from "../components/Splash";

const Index = () => {
  const router = useRouter();

  useEffect(() => {
    setTimeout(() => {
      router.push("/home");
    }, 3000);
  }, []);

  return (
    <>
      <Head>
        <title>Divisas app</title>
        <meta name="App divisas" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/logoDivisas.png" />
      </Head>
      <Splash />
    </>
  );
};

export default Index;
